<?php

namespace Tests;

use Creational\AbstractFactory\BenzCar;
use Creational\AbstractFactory\BMWCar;
use Creational\AbstractFactory\CarAbstractFactory;
use PHPUnit\Framework\TestCase;

class AbstractFactoryTest extends TestCase
{
    private $careFactory;
    protected function setUp(): void
{
    parent::setUp(); // TODO: Change the autogenerated stub
    $this->careFactory = new CarAbstractFactory(200000);
}

    public function testCanCreateBMWCar()
     {
         $myBMWCar = $this->careFactory->createBMWCar();
         $this->assertInstanceOf(BMWCar::class , $myBMWCar);

     }
     public function testCanCreateBenzCar(){
         $myBenzCar = $this->careFactory->createBenzCar();
         $this->assertInstanceOf(BenzCar::class , $myBenzCar,"car is not benz");
     }

}